<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <NoWarn>NETSDK1138;1591</NoWarn>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>ENCY</Authors>
    <PackageId>EncySoftware.DirectCladdingOperation</PackageId>
    <PackageTags>ency-extension;operationsolver</PackageTags>
    <Description>Operation for ENCY that calculates a toolpath for additive machining by directly transforming input geometric curves into tool movements at given speeds and with specified linking strategy parameters</Description>
    <PackageIcon>icon.png</PackageIcon>
    <PackageProjectUrl>https://github.com/EncySoftware/DirectCladdingOperation</PackageProjectUrl>
    <RepositoryUrl>https://github.com/EncySoftware/DirectCladdingOperation</RepositoryUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="EncySoftware.CAMAPI.SDK.Net" Version="2.0.24-dev.12" />
  </ItemGroup>

  <ItemGroup>
    <None Include="icon.png" Pack="true" PackagePath="\"/>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="DirectCladdingOperation_ExtOp.xml" Pack="true" PackagePath="contentFiles\any\any\">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="DirectCladdingOperationExtension.settings.json" Pack="true" PackagePath="contentFiles\any\any\">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
